### ISSUE TITLE
[Beginner][Translate] Components Document

### ISSUE THREAD

**Issue by bartdong** [OpenTenBase/OpenTenBase#35]
https://github.com/OpenTenBase/docs/blob/main/docs/guide/05-component.md
Needs to be translated into English and saved as 05-component.en.md

**Comment by enkilee** [comment]
Done
* https://github.com/OpenTenBase/docs/pull/19

**Comment by Rukai-Jiang** [comment]
Hi @bartdong, I'm Kevin Jiang, an OpenTenBase Campus Ambassador.

I checked the docs repository and confirmed that `docs/guide/05-component.en.md` is still missing. I'd like to translate the component documentation into English and submit a pull request for this issue.

I will preserve the original structure, commands, and technical terminology, and will carefully review the Markdown formatting before submitting.

**Comment by Rukai-Jiang** [comment]
Update: I found that OpenTenBase/docs#19 is already an open pull request for this issue. I won't create a duplicate PR.

If the maintainers would like help reviewing or finishing the existing translation, I'm happy to assist. Otherwise, I'll pick another unclaimed issue without an active pull request.
